############################
#       CONFIG PLUGIN      #
############################
plugin:
  enable: true
  prefix: ""

############################
#       GUI CONFIG         #
############################
gui:
  title: "§5Custom Sword"
############################
#       GUI CONFIG         #
############################
Cooldown:
  bypass-permission: "cs.bypass.cooldown"
  message: "Vous devez attendre {time}, avant de réutilisé cette capacité !"
CustomSword:
  PoisonSword:
    name: "&5PoisonSword"
    description:
      - "&4 20% de chance d'enpoisonée votre enemy !"
      - "&4Ne touche pas la lame sa coupeeee !"
    onHitPlayer:
      potionEffect:
        effect: "Poison"
        modifier: 1
        time: 15
        percentage: 20
  SlowSword:
    name: "&5SlowSword"
    description:
      - "&9Ma Super Epee tranche vraiment bien"
      - "&4Ne touche pas la lame sa coupeeee !"
    onHitPlayer:
      potionEffect:
        effect: "Poison"
        modifier: 1
        time: 15
        percentage: 20
  VampireSword:
    name: "&5VampireSword"
    description:
      - "&9Ma Super Epee tranche vraiment bien"
      - "&4Ne touche pas la lame sa coupeeee !"
    onHitPlayer:
      potionEffect:
        effect: "Poison"
        modifier: 1
        time: 15
        percentage: 20





