############################
#       CONFIG PLUGIN      #
############################
plugin:
  enable: true
  prefix: ""

############################
#       GUI CONFIG         #
############################
title: "ยง5Custom Sword"

